apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devsecops
  name: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/devsecops-role"
        vault.hashicorp.com/role: "devsecops-role"
      labels:
        app: devsecops
    spec:
      serviceAccountName: issuer
      initContainers:
      - name: db-check
        image: busybox:1.34
        command:
        - sh
        - -c
        - |
          until nc -zv mysql-service 3306; do
            echo "Waiting for database to be ready...";
            sleep 2;
          done;
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_PORT
          value: "3306"

      containers:
      - image: replace
        name: devsecops-container
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: vault-db-creds
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vault-db-creds
              key: password
        volumeMounts:
        - mountPath: /data
          name: mysql-data
        securityContext:
          runAsNonRoot: true
          runAsUser: 100
          readOnlyRootFilesystem: true
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: ebs-mysql-pv-claim
