apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devsecops
  name: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "devsecops-role"
        vault.hashicorp.com/agent-inject-secret-db-credentials: "database/creds/devsecops-role"
        vault.hashicorp.com/agent-inject-template-db-credentials: |
          {{- with secret "database/creds/devsecops-role" -}}
          export DB_USERNAME={{ .Data.username }}
          export DB_PASSWORD={{ .Data.password }}
          {{- end }}
      labels:
        app: devsecops
    spec:
      serviceAccountName: issuer
      initContainers:
      - name: db-check
        image: busybox:1.34
        command:
        - sh
        - -c
        - |
          until nc -zv mysql-service 3306; do
            echo "Waiting for database to be ready...";
            sleep 2;
          done;

      containers:
      - name: devsecops-container
        image: replace
        securityContext:
          runAsNonRoot: true
          runAsUser: 100
          readOnlyRootFilesystem: true
        command: ["/bin/sh", "-c"]
        args:
          - . /vault/secrets/db-credentials && java -jar /home/k8s-pipeline/app.jar
    
        volumeMounts:
        - name: mysql-data
          mountPath: /data
        - mountPath: /tmp
          name: vol
      volumes:
      - name: mysql-data
        emptyDir: {}
      - name: vol
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devsecops
  name: devsecops-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: devsecops
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 1Gi  
  storageClassName: ""  
