apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devsecops
  name: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/devsecops-role"
        vault.hashicorp.com/role: "devsecops-role"
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "database/creds/devsecops-role" -}}
          export DB_USERNAME="{{ .Data.username }}"
          export DB_PASSWORD="{{ .Data.password }}"
          {{- end }}
      labels:
        app: devsecops
    spec:
      serviceAccountName: issuer
      initContainers:
      - name: db-check
        image: busybox:1.34
        command:
        - sh
        - -c
        - |
          until nc -zv mysql-service 3306; do
            echo "Waiting for database to be ready...";
            sleep 2;
          done;

      containers:
      - name: devsecops-container
        image: replace
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_USERNAME
          valueFrom:
            fieldRef:
              fieldPath: /vault/secrets/db-creds.username
        - name: DB_PASSWORD
          valueFrom:
            fieldRef:
              fieldPath: /vault/secrets/db-creds.password
        volumeMounts:
        - name: mysql-data
          mountPath: /data
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: ebs-mysql-pv-claim
