apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceName: mysql-service
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword # Change to a secure password
        - name: MYSQL_DATABASE
          value: devsecopsdb
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        readOnlyRootFilesystem: false
      initContainers:
      - name: init-mysql-script
        image: busybox:1.34
        command: ['sh', '-c', 'cp /config/init.sql /docker-entrypoint-initdb.d/init.sql']
        volumeMounts:
        - name: init-script
          mountPath: /config
        - name: mysql-data
          mountPath: /docker-entrypoint-initdb.d
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: 
      - ReadWriteOnce
      storageClassName: ebs-sc
      resources:
        requests:
          storage: 10Gi
  volumes:
  - name: init-script
    configMap:
      name: mysql-init-script
