apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk # base64-encoded "rootpassword"
  MYSQL_DATABASE: ZGV2c2Vjb3BzZGI= # base64-encoded "devsecopsdb"