apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  labels:
    app: mysql
data:
  init.sql: |
    CREATE USER IF NOT EXISTS 'devuser'@'%' IDENTIFIED BY 'devpassword';
    GRANT ALL PRIVILEGES ON devsecopsdb.* TO 'devuser'@'%';
    FLUSH PRIVILEGES;